# Generated by Django 5.1.6 on 2025-02-25 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('suggested_interval_miles', models.PositiveIntegerField(blank=True, null=True)),
                ('suggested_interval_months', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Categories',
            },
        ),
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year_start', models.PositiveIntegerField(blank=True, null=True)),
                ('year_end', models.PositiveIntegerField(blank=True, null=True)),
                ('min_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancecategory')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('mileage_at_service', models.PositiveIntegerField()),
                ('service_provider', models.CharField(blank=True, max_length=255)),
                ('service_details', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='maintenance_receipts')),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancecategory')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due_soon', 'Due Soon'), ('overdue', 'Overdue'), ('completed', 'Completed')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('last_service_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('suggested_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.maintenancecategory')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='vehicles.vehicle')),
            ],
        ),
    ]
